(() => {
  "use strict";

  const languages = [
    ["en", "English"], ["hi", "हिन्दी"], ["kn", "ಕನ್ನಡ"], ["mr", "मराठी"], ["ta", "தமிழ்"],
    ["te", "తెలుగు"], ["ml", "മലയാളം"], ["or", "ଓଡ଼ିଆ"], ["bn", "বাংলা"], ["pa", "ਪੰਜਾਬੀ"], ["gu", "ગુજરાતી"],
  ];
  const translations = {
    en: { language: "Language", start: "Start", videos: "Videos", slides: "Slides", assessment: "Assessment", a1: "Activity 1", a2: "Activity 2", a3a: "Activity 3A", a3b: "Activity 3B", close: "Close", certificate: "Certificate", startHeading: "Start here", assessmentHeading: "Pre- and post-assessment", a1Heading: "Activity 1 · Compare before you trust", a2Heading: "Activity 2 · Build one shared plan", a3aHeading: "Activity 3A · Design an AI-supported IPE intervention", a3bHeading: "Activity 3B · Sustainability appraisal", closeHeading: "Close the loop", certificateHeading: "Certificate generator", videoHeading: "Video learning library · 10 videos", slidesHeading: "Interactive learning slideshow", slidesIntro: "Step through the learner deck at your own pace. Use the arrows, slide selector or keyboard shortcuts.", prev: "← Previous", next: "Next →", full: "Full screen", jump: "Jump to slide", download: "Download PPTX", verify: "Verify certificate", print: "Print certificate / Save as PDF", save: "Save in this browser", record: "Download learner record", signIn: "Email me a secure sign-in link" },
    hi: { language: "भाषा", start: "शुरुआत", videos: "वीडियो", slides: "स्लाइड्स", assessment: "मूल्यांकन", a1: "गतिविधि 1", a2: "गतिविधि 2", a3a: "गतिविधि 3A", a3b: "गतिविधि 3B", close: "समापन", certificate: "प्रमाणपत्र", startHeading: "यहाँ से शुरू करें", assessmentHeading: "पूर्व और पश्चात मूल्यांकन", a1Heading: "गतिविधि 1 · भरोसा करने से पहले तुलना करें", a2Heading: "गतिविधि 2 · एक साझा योजना बनाएँ", a3aHeading: "गतिविधि 3A · AI-सहायित IPE हस्तक्षेप डिज़ाइन", a3bHeading: "गतिविधि 3B · स्थिरता मूल्यांकन", closeHeading: "चक्र पूरा करें", certificateHeading: "प्रमाणपत्र जनरेटर", videoHeading: "वीडियो सीखने की लाइब्रेरी · 10 वीडियो", slidesHeading: "इंटरैक्टिव लर्निंग स्लाइड शो", slidesIntro: "अपनी गति से स्लाइड देखें। तीर, स्लाइड चयन या कीबोर्ड शॉर्टकट का उपयोग करें।", prev: "← पिछला", next: "अगला →", full: "पूर्ण स्क्रीन", jump: "स्लाइड चुनें", download: "PPTX डाउनलोड करें", verify: "प्रमाणपत्र सत्यापित करें", print: "प्रमाणपत्र प्रिंट / PDF", save: "इस ब्राउज़र में सहेजें", record: "लर्नर रिकॉर्ड डाउनलोड करें", signIn: "सुरक्षित साइन-इन लिंक ईमेल करें" },
    kn: { language: "ಭಾಷೆ", start: "ಪ್ರಾರಂಭ", videos: "ವೀಡಿಯೊಗಳು", slides: "ಸ್ಲೈಡ್‌ಗಳು", assessment: "ಮೌಲ್ಯಮಾಪನ", a1: "ಚಟುವಟಿಕೆ 1", a2: "ಚಟುವಟಿಕೆ 2", a3a: "ಚಟುವಟಿಕೆ 3A", a3b: "ಚಟುವಟಿಕೆ 3B", close: "ಮುಕ್ತಾಯ", certificate: "ಪ್ರಮಾಣಪತ್ರ", startHeading: "ಇಲ್ಲಿಂದ ಪ್ರಾರಂಭಿಸಿ", assessmentHeading: "ಪೂರ್ವ ಮತ್ತು ನಂತರದ ಮೌಲ್ಯಮಾಪನ", a1Heading: "ಚಟುವಟಿಕೆ 1 · ನಂಬುವ ಮೊದಲು ಹೋಲಿಸಿ", a2Heading: "ಚಟುವಟಿಕೆ 2 · ಒಂದು ಹಂಚಿಕೊಂಡ ಯೋಜನೆ", a3aHeading: "ಚಟುವಟಿಕೆ 3A · AI-ಸಹಾಯಿತ IPE ವಿನ್ಯಾಸ", a3bHeading: "ಚಟುವಟಿಕೆ 3B · ಸ್ಥಿರತೆ ಮೌಲ್ಯಮಾಪನ", closeHeading: "ಚಕ್ರವನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ", certificateHeading: "ಪ್ರಮಾಣಪತ್ರ ಜನರೇಟರ್", videoHeading: "ವೀಡಿಯೊ ಕಲಿಕಾ ಗ್ರಂಥಾಲಯ · 10 ವೀಡಿಯೊಗಳು", slidesHeading: "ಸಂವಾದಾತ್ಮಕ ಕಲಿಕಾ ಸ್ಲೈಡ್ ಶೋ", slidesIntro: "ನಿಮ್ಮ ವೇಗದಲ್ಲಿ ಸ್ಲೈಡ್‌ಗಳನ್ನು ನೋಡಿ. ಬಾಣಗಳು ಅಥವಾ ಸ್ಲೈಡ್ ಆಯ್ಕೆಯನ್ನು ಬಳಸಿ.", prev: "← ಹಿಂದಿನದು", next: "ಮುಂದಿನದು →", full: "ಪೂರ್ಣ ಪರದೆ", jump: "ಸ್ಲೈಡ್ ಆಯ್ಕೆ", download: "PPTX ಡೌನ್‌ಲೋಡ್", verify: "ಪ್ರಮಾಣಪತ್ರ ಪರಿಶೀಲಿಸಿ", print: "ಪ್ರಮಾಣಪತ್ರ ಮುದ್ರಿಸಿ / PDF", save: "ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಉಳಿಸಿ", record: "ಕಲಿಯುವವರ ದಾಖಲೆ ಡೌನ್‌ಲೋಡ್", signIn: "ಸುರಕ್ಷಿತ ಸೈನ್-ಇನ್ ಲಿಂಕ್ ಇಮೇಲ್ ಮಾಡಿ" },
    mr: { language: "भाषा", start: "सुरुवात", videos: "व्हिडिओ", slides: "स्लाइड्स", assessment: "मूल्यमापन", a1: "उपक्रम 1", a2: "उपक्रम 2", a3a: "उपक्रम 3A", a3b: "उपक्रम 3B", close: "समारोप", certificate: "प्रमाणपत्र", startHeading: "येथून सुरुवात करा", assessmentHeading: "पूर्व आणि पश्चात मूल्यमापन", a1Heading: "उपक्रम 1 · विश्वास ठेवण्यापूर्वी तुलना करा", a2Heading: "उपक्रम 2 · एक सामायिक योजना तयार करा", a3aHeading: "उपक्रम 3A · AI-सहाय्यित IPE हस्तक्षेप", a3bHeading: "उपक्रम 3B · शाश्वतता मूल्यमापन", closeHeading: "चक्र पूर्ण करा", certificateHeading: "प्रमाणपत्र जनरेटर", videoHeading: "व्हिडिओ शिकण्याची लायब्ररी · 10 व्हिडिओ", slidesHeading: "परस्परसंवादी शिक्षण स्लाइड शो", slidesIntro: "आपल्या गतीने स्लाइड्स पहा. बाण किंवा स्लाइड निवड वापरा.", prev: "← मागील", next: "पुढील →", full: "पूर्ण स्क्रीन", jump: "स्लाइड निवडा", download: "PPTX डाउनलोड", verify: "प्रमाणपत्र पडताळा", print: "प्रमाणपत्र प्रिंट / PDF", save: "या ब्राउझरमध्ये जतन करा", record: "शिकणाऱ्याचा रेकॉर्ड डाउनलोड", signIn: "सुरक्षित साइन-इन लिंक ईमेल करा" },
    ta: { language: "மொழி", start: "தொடக்கம்", videos: "வீடியோக்கள்", slides: "ஸ்லைட்கள்", assessment: "மதிப்பீடு", a1: "செயல் 1", a2: "செயல் 2", a3a: "செயல் 3A", a3b: "செயல் 3B", close: "முடிவு", certificate: "சான்றிதழ்", startHeading: "இங்கே தொடங்குங்கள்", assessmentHeading: "முன் மற்றும் பிந்தைய மதிப்பீடு", a1Heading: "செயல் 1 · நம்புவதற்கு முன் ஒப்பிடுங்கள்", a2Heading: "செயல் 2 · பகிரப்பட்ட திட்டம்", a3aHeading: "செயல் 3A · AI ஆதரவு IPE வடிவமைப்பு", a3bHeading: "செயல் 3B · நிலைத்தன்மை மதிப்பீடு", closeHeading: "சுழற்சியை முடிக்கவும்", certificateHeading: "சான்றிதழ் உருவாக்கி", videoHeading: "வீடியோ கற்றல் நூலகம் · 10 வீடியோக்கள்", slidesHeading: "இணையச்செயல் கற்றல் ஸ்லைடு ஷோ", slidesIntro: "உங்கள் வேகத்தில் ஸ்லைட்களைப் பாருங்கள். அம்புகள் அல்லது ஸ்லைடு தேர்வைப் பயன்படுத்துங்கள்.", prev: "← முந்தையது", next: "அடுத்தது →", full: "முழுத் திரை", jump: "ஸ்லைடு தேர்வு", download: "PPTX பதிவிறக்கம்", verify: "சான்றிதழைச் சரிபார்க்கவும்", print: "சான்றிதழ் அச்சிடு / PDF", save: "இந்த உலாவியில் சேமிக்கவும்", record: "கற்றுநர் பதிவிறக்கம்", signIn: "பாதுகாப்பான உள்நுழைவு இணைப்பை மின்னஞ்சல் செய்யவும்" },
    te: { language: "భాష", start: "ప్రారంభం", videos: "వీడియోలు", slides: "స్లైడ్లు", assessment: "మూల్యాంకనం", a1: "చర్య 1", a2: "చర్య 2", a3a: "చర్య 3A", a3b: "చర్య 3B", close: "ముగింపు", certificate: "సర్టిఫికేట్", startHeading: "ఇక్కడ ప్రారంభించండి", assessmentHeading: "ముందు మరియు తరువాత మూల్యాంకనం", a1Heading: "చర్య 1 · నమ్మే ముందు పోల్చండి", a2Heading: "చర్య 2 · భాగస్వామ్య ప్రణాళిక", a3aHeading: "చర్య 3A · AI సహిత IPE రూపకల్పన", a3bHeading: "చర్య 3B · స్థిరత్వ అంచనా", closeHeading: "చక్రాన్ని ముగించండి", certificateHeading: "సర్టిఫికేట్ జనరేటర్", videoHeading: "వీడియో అభ్యాస గ్రంథాలయం · 10 వీడియోలు", slidesHeading: "ఇంటరాక్టివ్ లెర్నింగ్ స్లైడ్ షో", slidesIntro: "మీ వేగంలో స్లైడ్లను చూడండి. బాణాలు లేదా స్లైడ్ ఎంపికను ఉపయోగించండి.", prev: "← మునుపటి", next: "తదుపరి →", full: "పూర్తి తెర", jump: "స్లైడ్ ఎంచుకోండి", download: "PPTX డౌన్‌లోడ్", verify: "సర్టిఫికేట్ ధృవీకరించండి", print: "సర్టిఫికేట్ ముద్రణ / PDF", save: "ఈ బ్రౌజర్‌లో సేవ్ చేయండి", record: "లెర్నర్ రికార్డు డౌన్‌లోడ్", signIn: "సురక్షిత సైన్-ఇన్ లింక్ ఇమెయిల్ చేయండి" },
    ml: { language: "ഭാഷ", start: "തുടക്കം", videos: "വീഡിയോകൾ", slides: "സ്ലൈഡുകൾ", assessment: "വിലയിരുത്തൽ", a1: "പ്രവർത്തനം 1", a2: "പ്രവർത്തനം 2", a3a: "പ്രവർത്തനം 3A", a3b: "പ്രവർത്തനം 3B", close: "സമാപനം", certificate: "സർട്ടിഫിക്കറ്റ്", startHeading: "ഇവിടെ തുടങ്ങുക", assessmentHeading: "മുൻ-ശേഷം വിലയിരുത്തൽ", a1Heading: "പ്രവർത്തനം 1 · വിശ്വസിക്കുന്നതിന് മുമ്പ് താരതമ്യം ചെയ്യുക", a2Heading: "പ്രവർത്തനം 2 · പങ്കിട്ട പദ്ധതി", a3aHeading: "പ്രവർത്തനം 3A · AI പിന്തുണയുള്ള IPE രൂപകൽപ്പന", a3bHeading: "പ്രവർത്തനം 3B · സുസ്ഥിരത വിലയിരുത്തൽ", closeHeading: "ചക്രം പൂർത്തിയാക്കുക", certificateHeading: "സർട്ടിഫിക്കറ്റ് ജനറേറ്റർ", videoHeading: "വീഡിയോ പഠന ലൈബ്രറി · 10 വീഡിയോകൾ", slidesHeading: "ഇന്ററാക്ടീവ് പഠന സ്ലൈഡ് ഷോ", slidesIntro: "നിങ്ങളുടെ വേഗത്തിൽ സ്ലൈഡുകൾ കാണുക. അമ്പുകൾ അല്ലെങ്കിൽ സ്ലൈഡ് തിരഞ്ഞെടുപ്പ് ഉപയോഗിക്കുക.", prev: "← മുമ്പത്തെ", next: "അടുത്തത് →", full: "പൂർണ്ണ സ്ക്രീൻ", jump: "സ്ലൈഡ് തിരഞ്ഞെടുക്കുക", download: "PPTX ഡൗൺലോഡ്", verify: "സർട്ടിഫിക്കറ്റ് പരിശോധിക്കുക", print: "സർട്ടിഫിക്കറ്റ് പ്രിന്റ് / PDF", save: "ഈ ബ്രൗസറിൽ സംരക്ഷിക്കുക", record: "പഠിതാവിന്റെ റെക്കോർഡ് ഡൗൺലോഡ്", signIn: "സുരക്ഷിത സൈൻ-ഇൻ ലിങ്ക് ഇമെയിൽ ചെയ്യുക" },
    or: { language: "ଭାଷା", start: "ଆରମ୍ଭ", videos: "ଭିଡିଓ", slides: "ସ୍ଲାଇଡ୍", assessment: "ମୂଲ୍ୟାୟନ", a1: "କାର୍ଯ୍ୟ 1", a2: "କାର୍ଯ୍ୟ 2", a3a: "କାର୍ଯ୍ୟ 3A", a3b: "କାର୍ଯ୍ୟ 3B", close: "ସମାପ୍ତି", certificate: "ପ୍ରମାଣପତ୍ର", startHeading: "ଏଠାରୁ ଆରମ୍ଭ କରନ୍ତୁ", assessmentHeading: "ପୂର୍ବ ଏବଂ ପରବର୍ତ୍ତୀ ମୂଲ୍ୟାୟନ", a1Heading: "କାର୍ଯ୍ୟ 1 · ବିଶ୍ୱାସ ପୂର୍ବରୁ ତୁଳନା କରନ୍ତୁ", a2Heading: "କାର୍ଯ୍ୟ 2 · ଏକ ସାମୂହିକ ଯୋଜନା", a3aHeading: "କାର୍ଯ୍ୟ 3A · AI ସହାୟିତ IPE ଡିଜାଇନ୍", a3bHeading: "କାର୍ଯ୍ୟ 3B · ସ୍ଥିରତା ମୂଲ୍ୟାୟନ", closeHeading: "ଚକ୍ର ଶେଷ କରନ୍ତୁ", certificateHeading: "ପ୍ରମାଣପତ୍ର ଜେନେରେଟର", videoHeading: "ଭିଡିଓ ଶିକ୍ଷା ଲାଇବ୍ରେରୀ · 10 ଭିଡିଓ", slidesHeading: "ଇଣ୍ଟରାକ୍ଟିଭ୍ ଶିକ୍ଷା ସ୍ଲାଇଡ୍ ଶୋ", slidesIntro: "ନିଜ ଗତିରେ ସ୍ଲାଇଡ୍ ଦେଖନ୍ତୁ। ତୀର କିମ୍ବା ସ୍ଲାଇଡ୍ ଚୟନ ବ୍ୟବହାର କରନ୍ତୁ।", prev: "← ପୂର୍ବ", next: "ପରବର୍ତ୍ତୀ →", full: "ପୂର୍ଣ୍ଣ ସ୍କ୍ରିନ୍", jump: "ସ୍ଲାଇଡ୍ ବାଛନ୍ତୁ", download: "PPTX ଡାଉନଲୋଡ୍", verify: "ପ୍ରମାଣପତ୍ର ଯାଞ୍ଚ", print: "ପ୍ରମାଣପତ୍ର ପ୍ରିଣ୍ଟ / PDF", save: "ଏହି ବ୍ରାଉଜରରେ ସଞ୍ଚୟ", record: "ଶିକ୍ଷାର୍ଥୀ ରେକର୍ଡ ଡାଉନଲୋଡ୍", signIn: "ସୁରକ୍ଷିତ ସାଇନ୍-ଇନ୍ ଲିଙ୍କ୍ ଇମେଲ୍ କରନ୍ତୁ" },
    bn: { language: "ভাষা", start: "শুরু", videos: "ভিডিও", slides: "স্লাইড", assessment: "মূল্যায়ন", a1: "কার্যক্রম ১", a2: "কার্যক্রম ২", a3a: "কার্যক্রম ৩A", a3b: "কার্যক্রম ৩B", close: "সমাপ্তি", certificate: "সনদ", startHeading: "এখান থেকে শুরু করুন", assessmentHeading: "পূর্ব ও পরবর্তী মূল্যায়ন", a1Heading: "কার্যক্রম ১ · বিশ্বাসের আগে তুলনা করুন", a2Heading: "কার্যক্রম ২ · একটি যৌথ পরিকল্পনা তৈরি করুন", a3aHeading: "কার্যক্রম ৩A · AI-সহায়িত IPE নকশা", a3bHeading: "কার্যক্রম ৩B · স্থায়িত্ব মূল্যায়ন", closeHeading: "চক্রটি সম্পূর্ণ করুন", certificateHeading: "সনদ জেনারেটর", videoHeading: "ভিডিও শেখার লাইব্রেরি · ১০টি ভিডিও", slidesHeading: "ইন্টার‌্যাক্টিভ লার্নিং স্লাইড শো", slidesIntro: "নিজের গতিতে স্লাইড দেখুন। তীর বা স্লাইড নির্বাচন ব্যবহার করুন।", prev: "← পূর্ববর্তী", next: "পরবর্তী →", full: "পূর্ণ পর্দা", jump: "স্লাইড বাছুন", download: "PPTX ডাউনলোড", verify: "সনদ যাচাই", print: "সনদ প্রিন্ট / PDF", save: "এই ব্রাউজারে সংরক্ষণ", record: "শিক্ষার্থীর রেকর্ড ডাউনলোড", signIn: "নিরাপদ সাইন-ইন লিঙ্ক ইমেল করুন" },
    pa: { language: "ਭਾਸ਼ਾ", start: "ਸ਼ੁਰੂ", videos: "ਵੀਡੀਓ", slides: "ਸਲਾਈਡਾਂ", assessment: "ਮੁਲਾਂਕਣ", a1: "ਗਤੀਵਿਧੀ 1", a2: "ਗਤੀਵਿਧੀ 2", a3a: "ਗਤੀਵਿਧੀ 3A", a3b: "ਗਤੀਵਿਧੀ 3B", close: "ਸਮਾਪਤੀ", certificate: "ਸਰਟੀਫਿਕੇਟ", startHeading: "ਇੱਥੋਂ ਸ਼ੁਰੂ ਕਰੋ", assessmentHeading: "ਪਹਿਲਾਂ ਅਤੇ ਬਾਅਦ ਦਾ ਮੁਲਾਂਕਣ", a1Heading: "ਗਤੀਵਿਧੀ 1 · ਭਰੋਸੇ ਤੋਂ ਪਹਿਲਾਂ ਤੁਲਨਾ ਕਰੋ", a2Heading: "ਗਤੀਵਿਧੀ 2 · ਸਾਂਝੀ ਯੋਜਨਾ ਬਣਾਓ", a3aHeading: "ਗਤੀਵਿਧੀ 3A · AI-ਸਹਾਇਤ IPE ਡਿਜ਼ਾਈਨ", a3bHeading: "ਗਤੀਵਿਧੀ 3B · ਟਿਕਾਊਪਣ ਮੁਲਾਂਕਣ", closeHeading: "ਚੱਕਰ ਪੂਰਾ ਕਰੋ", certificateHeading: "ਸਰਟੀਫਿਕੇਟ ਜਨਰੇਟਰ", videoHeading: "ਵੀਡੀਓ ਸਿੱਖਣ ਲਾਇਬ੍ਰੇਰੀ · 10 ਵੀਡੀਓ", slidesHeading: "ਇੰਟਰਐਕਟਿਵ ਲਰਨਿੰਗ ਸਲਾਈਡ ਸ਼ੋਅ", slidesIntro: "ਆਪਣੀ ਗਤੀ ਨਾਲ ਸਲਾਈਡਾਂ ਵੇਖੋ। ਤੀਰ ਜਾਂ ਸਲਾਈਡ ਚੋਣ ਵਰਤੋ।", prev: "← ਪਿਛਲਾ", next: "ਅਗਲਾ →", full: "ਪੂਰੀ ਸਕ੍ਰੀਨ", jump: "ਸਲਾਈਡ ਚੁਣੋ", download: "PPTX ਡਾਊਨਲੋਡ", verify: "ਸਰਟੀਫਿਕੇਟ ਜਾਂਚੋ", print: "ਸਰਟੀਫਿਕੇਟ ਪ੍ਰਿੰਟ / PDF", save: "ਇਸ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਕਰੋ", record: "ਸਿੱਖਿਆਰਥੀ ਰਿਕਾਰਡ ਡਾਊਨਲੋਡ", signIn: "ਸੁਰੱਖਿਅਤ ਸਾਈਨ-ਇਨ ਲਿੰਕ ਈਮੇਲ ਕਰੋ" },
    gu: { language: "ભાષા", start: "શરૂઆત", videos: "વિડિઓ", slides: "સ્લાઇડ્સ", assessment: "મૂલ્યાંકન", a1: "પ્રવૃત્તિ 1", a2: "પ્રવૃત્તિ 2", a3a: "પ્રવૃત્તિ 3A", a3b: "પ્રવૃત્તિ 3B", close: "સમાપન", certificate: "પ્રમાણપત્ર", startHeading: "અહીંથી શરૂ કરો", assessmentHeading: "પૂર્વ અને પછીનું મૂલ્યાંકન", a1Heading: "પ્રવૃત્તિ 1 · વિશ્વાસ પહેલાં સરખામણી કરો", a2Heading: "પ્રવૃત્તિ 2 · એક સંયુક્ત યોજના બનાવો", a3aHeading: "પ્રવૃત્તિ 3A · AI-સહાયિત IPE ડિઝાઇન", a3bHeading: "પ્રવૃત્તિ 3B · ટકાઉપણું મૂલ્યાંકન", closeHeading: "ચક્ર પૂર્ણ કરો", certificateHeading: "પ્રમાણપત્ર જનરેટર", videoHeading: "વિડિઓ લર્નિંગ લાઇબ્રેરી · 10 વિડિઓ", slidesHeading: "ઇન્ટરેક્ટિવ લર્નિંગ સ્લાઇડ શો", slidesIntro: "તમારી ગતિએ સ્લાઇડ જુઓ. તીર અથવા સ્લાઇડ પસંદગીનો ઉપયોગ કરો.", prev: "← પાછલું", next: "આગળ →", full: "પૂર્ણ સ્ક્રીન", jump: "સ્લાઇડ પસંદ કરો", download: "PPTX ડાઉનલોડ", verify: "પ્રમાણપત્ર ચકાસો", print: "પ્રમાણપત્ર પ્રિન્ટ / PDF", save: "આ બ્રાઉઝરમાં સાચવો", record: "શીખનાર રેકોર્ડ ડાઉનલોડ", signIn: "સુરક્ષિત સાઇન-ઇન લિંક ઇમેઇલ કરો" },
  };

  function addStyles() {
    if (document.getElementById("module-language-styles")) return;
    const style = document.createElement("style"); style.id = "module-language-styles";
    style.textContent = `#moduleLanguagePanel{display:flex;justify-content:flex-end;align-items:center;gap:.55rem;margin-top:1rem;color:#fff;font-size:.9rem}#moduleLanguagePanel label{margin:0;font-weight:700;color:#d9f4f3}#moduleLanguage{width:auto;min-width:10rem;padding:.45rem .65rem;border-radius:.4rem;border:1px solid #a7e7e4;background:#fff;color:#163a5f}@media(max-width:760px){#moduleLanguagePanel{justify-content:flex-start}}`;
    document.head.appendChild(style);
  }

  function addSelector() {
    if (document.getElementById("moduleLanguagePanel")) return;
    const header = document.querySelector("header"); if (!header) return;
    const panel = document.createElement("div"); panel.id = "moduleLanguagePanel"; panel.innerHTML = `<label for="moduleLanguage">${translations.en.language}</label><select id="moduleLanguage" aria-label="${translations.en.language}">${languages.map(([code, name]) => `<option value="${code}">${name}</option>`).join("")}</select>`;
    header.appendChild(panel);
    const select = panel.querySelector("select"); select.value = localStorage.getItem("module-language") || "en"; select.addEventListener("change", () => { localStorage.setItem("module-language", select.value); apply(select.value); });
  }

  function setText(selector, value) { const node = document.querySelector(selector); if (node) node.textContent = value; }
  function setLabel(selector, value) { const node = document.querySelector(selector); if (!node) return; const textNode = [...node.childNodes].reverse().find((child) => child.nodeType === Node.TEXT_NODE && child.textContent.trim()); if (textNode) textNode.textContent = ` ${value}`; else node.append(` ${value}`); }

  function apply(code) {
    const t = translations[code] || translations.en; document.documentElement.lang = code; document.body.dataset.language = code;
    const nav = { "#start": "start", "#video-library": "videos", "#learning-slideshow": "slides", "#assessment": "assessment", "#a1": "a1", "#a2": "a2", "#a3a": "a3a", "#a3b": "a3b", "#close": "close", "#certificate": "certificate" };
    Object.entries(nav).forEach(([href, key]) => { const item = document.querySelector(`nav a[href="${href}"]`); if (item) item.textContent = t[key]; });
    [["#start h2", "startHeading"], ["#assessment h2", "assessmentHeading"], ["#a1 h2", "a1Heading"], ["#a2 h2", "a2Heading"], ["#a3a h2", "a3aHeading"], ["#a3b h2", "a3bHeading"], ["#close h2", "closeHeading"], ["#certificate h2", "certificateHeading"], ["#video-library h2", "videoHeading"], ["#learning-slideshow h2", "slidesHeading"]].forEach(([selector, key]) => setText(selector, t[key]));
    setText("#learning-slideshow .ls-head p", t.slidesIntro); setText("#lsPrev", t.prev); setText("#lsNext", t.next); setText("#lsFull", t.full); setText("#learning-slideshow .ls-download", t.download); setLabel('label[for="lsSelect"]', t.jump); setText("#verifyCertificateButton", t.verify); setText("#printCertificateButton", t.print); setText("#sendMagicLink", t.signIn); setText("#saveCloudRecord", t.save); setText("#downloadRecord", t.record);
    const languageLabel = document.querySelector("#moduleLanguagePanel label"); if (languageLabel) languageLabel.textContent = t.language; const select = document.getElementById("moduleLanguage"); if (select) select.setAttribute("aria-label", t.language);
    document.dispatchEvent(new CustomEvent("module-language-change", { detail: { code, translations: t } }));
  }

  addStyles(); addSelector(); apply(document.getElementById("moduleLanguage")?.value || "en");
})();
